import type { Locale } from "@/lib/i18n/preferences";
import type { LegalDocument } from "@/lib/legal/types";

/** `{name}` is replaced with the product name when rendered. */
export const PRIVACY_POLICY: Record<Locale, LegalDocument> = {
  en: {
    title: "Privacy Policy",
    description: "Privacy Policy for {name}.",
    blocks: [
      { p: 'This Privacy Policy describes how {name} ("we," "us," or "our") collects, uses, and stores information when you use our CV generation service (the "Service"). This document is provided for transparency. [PLACEHOLDER: have qualified legal counsel review and finalize this policy for your jurisdiction and business structure.]' },
      { h: "Information we collect" },
      { p: "We collect information you provide directly, information generated through your use of the Service, and limited technical data needed to operate the application." },
      { h: "Account information" },
      { p: "When you register, we collect details such as your name, email address, and a hashed password (for email/password sign-in). If you use Google OAuth, we receive profile information made available by Google (such as name, email, and profile image) according to your Google account settings." },
      { h: "CV and resume content" },
      { p: "Content you enter into the CV builder, including employment history, education, skills, summaries, and related fields, is stored so you can edit, save, and export your CVs. You control what you submit." },
      { h: "Authentication information" },
      { p: "We use Auth.js (NextAuth) with JWT-based sessions. Session tokens and related authentication data are used to keep you signed in and to protect access to your account and CVs." },
      { h: "AI processing" },
      { p: "When AI features are enabled and you choose to use them, relevant text you submit (such as summaries or experience descriptions) may be sent to a configured AI provider (for example, an OpenAI-compatible API) to generate suggestions. You must accept suggestions before they are applied. Do not submit sensitive personal data you do not want processed by third-party AI services." },
      { h: "PDF generation" },
      { p: "PDF export is generated on our servers from your saved CV data and selected template. Export requests require authentication and ownership checks; we do not generate PDFs from arbitrary client-supplied content without those controls." },
      { h: "How we use information" },
      { ul: ["Provide, maintain, and improve the Service", "Authenticate users and enforce access to CVs", "Save and sync your CV content", "Generate AI suggestions when you request them", "Produce PDF exports when you request them", "Respond to support or legal requests where applicable"] },
      { h: "Data storage" },
      { p: "Account and CV data are stored in MongoDB (or a compatible database) hosted by a provider you configure for deployment (for example, MongoDB Atlas). Data location depends on your database hosting region and provider settings." },
      { h: "Third-party services" },
      { p: "The Service may rely on third parties such as:" },
      { ul: ["Hosting (for example, Vercel)", "Database hosting (for example, MongoDB Atlas)", "Authentication (Google OAuth when enabled)", "AI providers (when API keys are configured)"] },
      { p: "Each provider processes data according to its own terms and privacy policies. [PLACEHOLDER: list the specific vendors and links you use in production.]" },
      { h: "Google OAuth" },
      { p: "If you sign in with Google, Google processes your authentication according to Google's policies. We receive limited profile information to create or update your account as described above." },
      { h: "Cookies and session technologies" },
      { p: "We use cookies or similar session mechanisms required for sign-in and security, and to remember your language, theme and appearance preferences. These are essential or functional rather than advertising tracking." },
      { h: "Data retention" },
      { p: "We retain account and CV data while your account is active and as needed to provide the Service. [PLACEHOLDER: define retention periods, backup retention, and deletion practices with legal advice.]" },
      { h: "Security" },
      { p: "We use industry-standard measures such as password hashing, server-side access controls, and ownership checks on CV operations. No method of transmission or storage is completely secure." },
      { h: "Your rights" },
      { p: "Depending on where you live, you may have rights to access, correct, delete, or export personal data. [PLACEHOLDER: describe how users can exercise rights and any regional requirements after legal review. We do not claim compliance with GDPR, CCPA, or other regimes unless formally established.]" },
      { h: "Children's privacy" },
      { p: "The Service is not directed to children under 13 (or the minimum age in your jurisdiction). We do not knowingly collect personal information from children. [PLACEHOLDER: adjust age threshold per applicable law.]" },
      { h: "Changes to this policy" },
      { p: 'We may update this Privacy Policy from time to time. We will post the updated version on this page and update the "Last updated" date. [PLACEHOLDER: describe how you will notify users of material changes.]' },
      { h: "Contact" },
      { p: "For privacy questions or requests, contact: [PLACEHOLDER: privacy contact email or web form]. [PLACEHOLDER: do not list a legal entity address until confirmed with counsel.]" },
    ],
  },
  es: {
    title: "Política de privacidad",
    description: "Política de privacidad de {name}.",
    blocks: [
      { p: 'Esta Política de privacidad describe cómo {name} ("nosotros") recopila, utiliza y almacena información cuando usas nuestro servicio de creación de CV (el "Servicio"). Este documento se ofrece con fines de transparencia. [PLACEHOLDER: un asesor jurídico cualificado debe revisar y finalizar esta política para tu jurisdicción y estructura empresarial.]' },
      { h: "Información que recopilamos" },
      { p: "Recopilamos la información que nos proporcionas directamente, la que se genera con el uso del Servicio y datos técnicos limitados necesarios para que la aplicación funcione." },
      { h: "Información de la cuenta" },
      { p: "Al registrarte, recopilamos datos como tu nombre, tu correo electrónico y una contraseña cifrada (para el inicio de sesión con correo y contraseña). Si usas Google OAuth, recibimos la información de perfil que Google pone a disposición (como nombre, correo e imagen de perfil) según la configuración de tu cuenta de Google." },
      { h: "Contenido del CV y del currículum" },
      { p: "El contenido que introduces en el editor de CV, incluidos el historial laboral, la formación, las habilidades, los resúmenes y campos relacionados, se almacena para que puedas editar, guardar y exportar tus CV. Tú decides qué envías." },
      { h: "Información de autenticación" },
      { p: "Usamos Auth.js (NextAuth) con sesiones basadas en JWT. Los tokens de sesión y los datos de autenticación relacionados sirven para mantener tu sesión iniciada y proteger el acceso a tu cuenta y a tus CV." },
      { h: "Procesamiento con IA" },
      { p: "Cuando las funciones de IA están activadas y decides usarlas, el texto pertinente que envías (como resúmenes o descripciones de experiencia) puede enviarse a un proveedor de IA configurado (por ejemplo, una API compatible con OpenAI) para generar sugerencias. Debes aceptar las sugerencias antes de que se apliquen. No envíes datos personales sensibles que no quieras que procesen servicios de IA de terceros." },
      { h: "Generación de PDF" },
      { p: "La exportación a PDF se genera en nuestros servidores a partir de los datos guardados de tu CV y de la plantilla seleccionada. Las solicitudes de exportación requieren autenticación y comprobaciones de propiedad; no generamos PDF a partir de contenido arbitrario enviado por el cliente sin esos controles." },
      { h: "Cómo usamos la información" },
      { ul: ["Prestar, mantener y mejorar el Servicio", "Autenticar a los usuarios y controlar el acceso a los CV", "Guardar y sincronizar el contenido de tus CV", "Generar sugerencias de IA cuando las solicites", "Crear exportaciones PDF cuando las solicites", "Responder a solicitudes de soporte o legales cuando corresponda"] },
      { h: "Almacenamiento de datos" },
      { p: "Los datos de la cuenta y de los CV se almacenan en MongoDB (o una base de datos compatible) alojada por el proveedor configurado para el despliegue (por ejemplo, MongoDB Atlas). La ubicación de los datos depende de la región de alojamiento y de la configuración del proveedor." },
      { h: "Servicios de terceros" },
      { p: "El Servicio puede depender de terceros como:" },
      { ul: ["Alojamiento (por ejemplo, Vercel)", "Alojamiento de bases de datos (por ejemplo, MongoDB Atlas)", "Autenticación (Google OAuth cuando está activado)", "Proveedores de IA (cuando hay claves de API configuradas)"] },
      { p: "Cada proveedor trata los datos según sus propias condiciones y políticas de privacidad. [PLACEHOLDER: indicar los proveedores concretos y sus enlaces en producción.]" },
      { h: "Google OAuth" },
      { p: "Si inicias sesión con Google, Google procesa tu autenticación según sus políticas. Recibimos información de perfil limitada para crear o actualizar tu cuenta como se describe arriba." },
      { h: "Cookies y tecnologías de sesión" },
      { p: "Usamos cookies o mecanismos de sesión similares necesarios para el inicio de sesión y la seguridad, y para recordar tus preferencias de idioma, tema y apariencia. Son esenciales o funcionales, no de seguimiento publicitario." },
      { h: "Conservación de datos" },
      { p: "Conservamos los datos de la cuenta y de los CV mientras tu cuenta esté activa y según sea necesario para prestar el Servicio. [PLACEHOLDER: definir plazos de conservación, copias de seguridad y prácticas de eliminación con asesoramiento jurídico.]" },
      { h: "Seguridad" },
      { p: "Aplicamos medidas estándar del sector, como el cifrado de contraseñas, controles de acceso en el servidor y comprobaciones de propiedad en las operaciones con CV. Ningún método de transmisión o almacenamiento es completamente seguro." },
      { h: "Tus derechos" },
      { p: "Según dónde residas, puedes tener derecho a acceder, rectificar, eliminar o exportar tus datos personales. [PLACEHOLDER: describir cómo ejercer los derechos y los requisitos regionales tras la revisión jurídica. No afirmamos cumplir el RGPD, la CCPA u otros regímenes salvo que se establezca formalmente.]" },
      { h: "Privacidad de menores" },
      { p: "El Servicio no está dirigido a menores de 13 años (o de la edad mínima de tu jurisdicción). No recopilamos a sabiendas información personal de menores. [PLACEHOLDER: ajustar la edad mínima según la ley aplicable.]" },
      { h: "Cambios en esta política" },
      { p: 'Podemos actualizar esta Política de privacidad periódicamente. Publicaremos la versión actualizada en esta página y modificaremos la fecha de "Última actualización". [PLACEHOLDER: describir cómo se notificarán los cambios importantes.]' },
      { h: "Contacto" },
      { p: "Para consultas o solicitudes sobre privacidad, contacta con: [PLACEHOLDER: correo o formulario de contacto de privacidad]. [PLACEHOLDER: no indicar la dirección de la entidad legal hasta confirmarla con un asesor.]" },
    ],
  },
  fr: {
    title: "Politique de confidentialité",
    description: "Politique de confidentialité de {name}.",
    blocks: [
      { p: "La présente Politique de confidentialité décrit comment {name} (« nous ») collecte, utilise et conserve les informations lorsque vous utilisez notre service de création de CV (le « Service »). Ce document est fourni dans un souci de transparence. [PLACEHOLDER : faire relire et finaliser cette politique par un juriste qualifié pour votre juridiction et votre structure.]" },
      { h: "Informations que nous collectons" },
      { p: "Nous collectons les informations que vous nous fournissez directement, celles générées par votre utilisation du Service et un nombre limité de données techniques nécessaires au fonctionnement de l'application." },
      { h: "Informations de compte" },
      { p: "Lors de votre inscription, nous collectons des informations telles que votre nom, votre adresse e-mail et un mot de passe haché (pour la connexion par e-mail et mot de passe). Si vous utilisez Google OAuth, nous recevons les informations de profil mises à disposition par Google (nom, e-mail, photo de profil) selon les paramètres de votre compte Google." },
      { h: "Contenu des CV" },
      { p: "Le contenu que vous saisissez dans l'éditeur, notamment votre parcours professionnel, vos formations, compétences, résumés et champs associés, est conservé afin que vous puissiez modifier, enregistrer et exporter vos CV. Vous maîtrisez ce que vous transmettez." },
      { h: "Informations d'authentification" },
      { p: "Nous utilisons Auth.js (NextAuth) avec des sessions basées sur JWT. Les jetons de session et les données d'authentification associées servent à maintenir votre connexion et à protéger l'accès à votre compte et à vos CV." },
      { h: "Traitement par l'IA" },
      { p: "Lorsque les fonctions d'IA sont activées et que vous choisissez de les utiliser, le texte concerné (résumés, descriptions d'expérience, etc.) peut être transmis à un fournisseur d'IA configuré (par exemple une API compatible OpenAI) afin de générer des suggestions. Vous devez accepter les suggestions avant qu'elles ne soient appliquées. Ne transmettez pas de données personnelles sensibles que vous ne souhaitez pas voir traitées par des services d'IA tiers." },
      { h: "Génération de PDF" },
      { p: "L'export PDF est généré sur nos serveurs à partir des données enregistrées de votre CV et du modèle choisi. Les demandes d'export exigent une authentification et un contrôle de propriété ; nous ne générons pas de PDF à partir de contenus arbitraires fournis par le client sans ces contrôles." },
      { h: "Utilisation des informations" },
      { ul: ["Fournir, maintenir et améliorer le Service", "Authentifier les utilisateurs et contrôler l'accès aux CV", "Enregistrer et synchroniser le contenu de vos CV", "Générer des suggestions d'IA à votre demande", "Produire des exports PDF à votre demande", "Répondre aux demandes d'assistance ou légales le cas échéant"] },
      { h: "Stockage des données" },
      { p: "Les données de compte et de CV sont stockées dans MongoDB (ou une base compatible) hébergée par le prestataire configuré pour le déploiement (par exemple MongoDB Atlas). L'emplacement des données dépend de la région d'hébergement et des paramètres du prestataire." },
      { h: "Services tiers" },
      { p: "Le Service peut s'appuyer sur des tiers tels que :" },
      { ul: ["Hébergement (par exemple Vercel)", "Hébergement de base de données (par exemple MongoDB Atlas)", "Authentification (Google OAuth lorsqu'il est activé)", "Fournisseurs d'IA (lorsque des clés d'API sont configurées)"] },
      { p: "Chaque prestataire traite les données selon ses propres conditions et politiques de confidentialité. [PLACEHOLDER : lister les prestataires et liens utilisés en production.]" },
      { h: "Google OAuth" },
      { p: "Si vous vous connectez avec Google, Google traite votre authentification conformément à ses politiques. Nous recevons des informations de profil limitées pour créer ou mettre à jour votre compte comme décrit ci-dessus." },
      { h: "Cookies et technologies de session" },
      { p: "Nous utilisons des cookies ou mécanismes de session similaires nécessaires à la connexion et à la sécurité, ainsi qu'à la mémorisation de vos préférences de langue, de thème et d'apparence. Ils sont essentiels ou fonctionnels, et non publicitaires." },
      { h: "Conservation des données" },
      { p: "Nous conservons les données de compte et de CV tant que votre compte est actif et autant que nécessaire pour fournir le Service. [PLACEHOLDER : définir les durées de conservation, de sauvegarde et les pratiques de suppression avec un conseil juridique.]" },
      { h: "Sécurité" },
      { p: "Nous appliquons des mesures conformes aux standards du secteur, comme le hachage des mots de passe, des contrôles d'accès côté serveur et des vérifications de propriété sur les opérations liées aux CV. Aucune méthode de transmission ou de stockage n'est totalement sûre." },
      { h: "Vos droits" },
      { p: "Selon votre lieu de résidence, vous pouvez disposer de droits d'accès, de rectification, de suppression ou d'export de vos données personnelles. [PLACEHOLDER : décrire l'exercice des droits et les exigences régionales après revue juridique. Nous ne revendiquons pas la conformité au RGPD, au CCPA ou à d'autres régimes sauf établissement formel.]" },
      { h: "Protection des mineurs" },
      { p: "Le Service ne s'adresse pas aux enfants de moins de 13 ans (ou de l'âge minimum de votre juridiction). Nous ne collectons pas sciemment d'informations personnelles sur des enfants. [PLACEHOLDER : ajuster l'âge minimum selon la loi applicable.]" },
      { h: "Modifications de cette politique" },
      { p: "Nous pouvons mettre à jour cette Politique de confidentialité. La version mise à jour sera publiée sur cette page avec une nouvelle date de « Dernière mise à jour ». [PLACEHOLDER : décrire comment les modifications importantes seront notifiées.]" },
      { h: "Contact" },
      { p: "Pour toute question ou demande relative à la confidentialité, contactez : [PLACEHOLDER : e-mail ou formulaire de contact]. [PLACEHOLDER : ne pas indiquer l'adresse de l'entité juridique avant validation par un juriste.]" },
    ],
  },
  de: {
    title: "Datenschutzerklärung",
    description: "Datenschutzerklärung von {name}.",
    blocks: [
      { p: "Diese Datenschutzerklärung beschreibt, wie {name} („wir“) Informationen erhebt, nutzt und speichert, wenn Sie unseren Dienst zur Erstellung von Lebensläufen (den „Dienst“) nutzen. Dieses Dokument dient der Transparenz. [PLACEHOLDER: Diese Erklärung von einer qualifizierten Rechtsberatung für Ihre Rechtsordnung und Unternehmensstruktur prüfen und finalisieren lassen.]" },
      { h: "Welche Informationen wir erheben" },
      { p: "Wir erheben Informationen, die Sie uns direkt bereitstellen, Informationen, die bei der Nutzung des Dienstes entstehen, sowie begrenzte technische Daten, die für den Betrieb der Anwendung erforderlich sind." },
      { h: "Kontoinformationen" },
      { p: "Bei der Registrierung erheben wir Angaben wie Ihren Namen, Ihre E-Mail-Adresse und ein gehashtes Passwort (für die Anmeldung mit E-Mail und Passwort). Wenn Sie Google OAuth nutzen, erhalten wir die von Google bereitgestellten Profilinformationen (z. B. Name, E-Mail-Adresse und Profilbild) gemäß Ihren Google-Kontoeinstellungen." },
      { h: "Inhalte von Lebensläufen" },
      { p: "Inhalte, die Sie im Editor eingeben – darunter Berufserfahrung, Ausbildung, Fähigkeiten, Zusammenfassungen und zugehörige Felder –, werden gespeichert, damit Sie Ihre Lebensläufe bearbeiten, speichern und exportieren können. Sie entscheiden, was Sie übermitteln." },
      { h: "Authentifizierungsdaten" },
      { p: "Wir verwenden Auth.js (NextAuth) mit JWT-basierten Sitzungen. Sitzungstoken und zugehörige Authentifizierungsdaten dienen dazu, Sie angemeldet zu halten und den Zugriff auf Ihr Konto und Ihre Lebensläufe zu schützen." },
      { h: "KI-Verarbeitung" },
      { p: "Wenn KI-Funktionen aktiviert sind und Sie diese nutzen, kann der betreffende Text (z. B. Zusammenfassungen oder Tätigkeitsbeschreibungen) an einen konfigurierten KI-Anbieter (etwa eine OpenAI-kompatible API) gesendet werden, um Vorschläge zu erzeugen. Vorschläge werden erst übernommen, wenn Sie sie bestätigen. Übermitteln Sie keine sensiblen personenbezogenen Daten, die nicht von KI-Diensten Dritter verarbeitet werden sollen." },
      { h: "PDF-Erstellung" },
      { p: "Der PDF-Export wird auf unseren Servern aus Ihren gespeicherten Lebenslaufdaten und der gewählten Vorlage erzeugt. Exportanfragen erfordern eine Authentifizierung und Eigentumsprüfung; ohne diese Kontrollen erzeugen wir keine PDFs aus beliebigen, vom Client gelieferten Inhalten." },
      { h: "Wie wir Informationen nutzen" },
      { ul: ["Den Dienst bereitstellen, betreiben und verbessern", "Nutzer authentifizieren und den Zugriff auf Lebensläufe absichern", "Ihre Lebenslaufinhalte speichern und synchronisieren", "KI-Vorschläge auf Ihre Anfrage erzeugen", "PDF-Exporte auf Ihre Anfrage erstellen", "Gegebenenfalls auf Support- oder rechtliche Anfragen reagieren"] },
      { h: "Datenspeicherung" },
      { p: "Konto- und Lebenslaufdaten werden in MongoDB (oder einer kompatiblen Datenbank) gespeichert, die von dem für den Betrieb konfigurierten Anbieter gehostet wird (z. B. MongoDB Atlas). Der Speicherort hängt von der Hosting-Region und den Anbietereinstellungen ab." },
      { h: "Dienste Dritter" },
      { p: "Der Dienst kann auf Dritte zurückgreifen, etwa:" },
      { ul: ["Hosting (z. B. Vercel)", "Datenbank-Hosting (z. B. MongoDB Atlas)", "Authentifizierung (Google OAuth, sofern aktiviert)", "KI-Anbieter (sofern API-Schlüssel konfiguriert sind)"] },
      { p: "Jeder Anbieter verarbeitet Daten nach seinen eigenen Bedingungen und Datenschutzrichtlinien. [PLACEHOLDER: konkrete Anbieter und Links für den Produktivbetrieb angeben.]" },
      { h: "Google OAuth" },
      { p: "Wenn Sie sich mit Google anmelden, verarbeitet Google Ihre Authentifizierung gemäß den eigenen Richtlinien. Wir erhalten begrenzte Profilinformationen, um Ihr Konto wie oben beschrieben anzulegen oder zu aktualisieren." },
      { h: "Cookies und Sitzungstechnologien" },
      { p: "Wir verwenden Cookies oder ähnliche Sitzungsmechanismen, die für Anmeldung und Sicherheit erforderlich sind, sowie um Ihre Einstellungen zu Sprache, Design und Darstellung zu speichern. Sie sind technisch notwendig oder funktional und dienen nicht der Werbeverfolgung." },
      { h: "Speicherdauer" },
      { p: "Wir speichern Konto- und Lebenslaufdaten, solange Ihr Konto aktiv ist und soweit dies zur Bereitstellung des Dienstes erforderlich ist. [PLACEHOLDER: Aufbewahrungsfristen, Backup-Aufbewahrung und Löschpraxis mit Rechtsberatung festlegen.]" },
      { h: "Sicherheit" },
      { p: "Wir setzen branchenübliche Maßnahmen ein, etwa Passwort-Hashing, serverseitige Zugriffskontrollen und Eigentumsprüfungen bei Lebenslauf-Vorgängen. Keine Übertragungs- oder Speichermethode ist vollständig sicher." },
      { h: "Ihre Rechte" },
      { p: "Je nach Wohnort haben Sie möglicherweise das Recht, auf Ihre personenbezogenen Daten zuzugreifen, sie zu berichtigen, zu löschen oder zu exportieren. [PLACEHOLDER: nach rechtlicher Prüfung beschreiben, wie Rechte ausgeübt werden und welche regionalen Anforderungen gelten. Wir behaupten keine Konformität mit DSGVO, CCPA oder anderen Regelwerken, sofern diese nicht formal festgestellt ist.]" },
      { h: "Datenschutz von Kindern" },
      { p: "Der Dienst richtet sich nicht an Kinder unter 13 Jahren (bzw. unter dem in Ihrer Rechtsordnung geltenden Mindestalter). Wir erheben wissentlich keine personenbezogenen Daten von Kindern. [PLACEHOLDER: Altersgrenze gemäß geltendem Recht anpassen.]" },
      { h: "Änderungen dieser Erklärung" },
      { p: "Wir können diese Datenschutzerklärung von Zeit zu Zeit aktualisieren. Die aktualisierte Fassung wird auf dieser Seite veröffentlicht und das Datum „Zuletzt aktualisiert“ angepasst. [PLACEHOLDER: beschreiben, wie Nutzer über wesentliche Änderungen informiert werden.]" },
      { h: "Kontakt" },
      { p: "Bei Fragen oder Anliegen zum Datenschutz wenden Sie sich an: [PLACEHOLDER: E-Mail oder Kontaktformular für Datenschutz]. [PLACEHOLDER: Anschrift der juristischen Person erst nach Bestätigung durch Rechtsberatung angeben.]" },
    ],
  },
  ar: {
    title: "سياسة الخصوصية",
    description: "سياسة الخصوصية الخاصة بـ {name}.",
    blocks: [
      { p: "توضح سياسة الخصوصية هذه كيف تجمع {name} (\"نحن\") المعلومات وتستخدمها وتخزنها عند استخدامك لخدمة إنشاء السير الذاتية (\"الخدمة\"). يُقدَّم هذا المستند بغرض الشفافية. [PLACEHOLDER: يجب أن يراجع مستشار قانوني مؤهل هذه السياسة ويعتمدها وفق نطاقك القضائي وهيكل نشاطك التجاري.]" },
      { h: "المعلومات التي نجمعها" },
      { p: "نجمع المعلومات التي تقدمها لنا مباشرة، والمعلومات الناتجة عن استخدامك للخدمة، وبيانات تقنية محدودة لازمة لتشغيل التطبيق." },
      { h: "معلومات الحساب" },
      { p: "عند التسجيل، نجمع بيانات مثل اسمك وبريدك الإلكتروني وكلمة مرور مُجزّأة (لتسجيل الدخول بالبريد الإلكتروني وكلمة المرور). وإذا استخدمت Google OAuth، فإننا نتلقى معلومات الملف الشخصي التي توفرها Google (مثل الاسم والبريد الإلكتروني وصورة الملف الشخصي) وفقًا لإعدادات حسابك في Google." },
      { h: "محتوى السيرة الذاتية" },
      { p: "يُخزَّن المحتوى الذي تُدخله في محرر السيرة الذاتية، بما في ذلك السجل الوظيفي والتعليم والمهارات والملخصات والحقول ذات الصلة، لتتمكن من تعديل سيرك الذاتية وحفظها وتصديرها. أنت من يتحكم فيما تُرسله." },
      { h: "معلومات المصادقة" },
      { p: "نستخدم Auth.js (NextAuth) مع جلسات تعتمد على JWT. تُستخدم رموز الجلسة وبيانات المصادقة المرتبطة بها لإبقائك مسجلًا الدخول وحماية الوصول إلى حسابك وسيرك الذاتية." },
      { h: "المعالجة بالذكاء الاصطناعي" },
      { p: "عند تفعيل ميزات الذكاء الاصطناعي واختيارك استخدامها، قد يُرسَل النص ذو الصلة الذي تقدمه (مثل الملخصات أو أوصاف الخبرة) إلى مزوّد ذكاء اصطناعي مُعدّ (مثل واجهة برمجية متوافقة مع OpenAI) لإنشاء اقتراحات. يجب أن توافق على الاقتراحات قبل تطبيقها. لا تُرسل بيانات شخصية حساسة لا ترغب في أن تعالجها خدمات ذكاء اصطناعي تابعة لجهات خارجية." },
      { h: "إنشاء ملفات PDF" },
      { p: "يُنشأ ملف PDF على خوادمنا من بيانات سيرتك الذاتية المحفوظة والقالب المحدد. تتطلب طلبات التصدير المصادقة والتحقق من الملكية، ولا ننشئ ملفات PDF من محتوى عشوائي يرسله العميل دون هذه الضوابط." },
      { h: "كيف نستخدم المعلومات" },
      { ul: ["تقديم الخدمة وصيانتها وتحسينها", "مصادقة المستخدمين وضبط الوصول إلى السير الذاتية", "حفظ محتوى سيرتك الذاتية ومزامنته", "إنشاء اقتراحات الذكاء الاصطناعي عند طلبك", "إنشاء ملفات PDF عند طلبك", "الرد على طلبات الدعم أو الطلبات القانونية عند الاقتضاء"] },
      { h: "تخزين البيانات" },
      { p: "تُخزَّن بيانات الحساب والسير الذاتية في MongoDB (أو قاعدة بيانات متوافقة) يستضيفها المزوّد المُعدّ للنشر (مثل MongoDB Atlas). يعتمد موقع البيانات على منطقة استضافة قاعدة البيانات وإعدادات المزوّد." },
      { h: "خدمات الجهات الخارجية" },
      { p: "قد تعتمد الخدمة على جهات خارجية مثل:" },
      { ul: ["الاستضافة (مثل Vercel)", "استضافة قواعد البيانات (مثل MongoDB Atlas)", "المصادقة (Google OAuth عند تفعيله)", "مزوّدو الذكاء الاصطناعي (عند إعداد مفاتيح الواجهة البرمجية)"] },
      { p: "يعالج كل مزوّد البيانات وفق شروطه وسياسات الخصوصية الخاصة به. [PLACEHOLDER: أدرج المزوّدين المحددين وروابطهم في بيئة الإنتاج.]" },
      { h: "Google OAuth" },
      { p: "إذا سجّلت الدخول باستخدام Google، فإن Google تعالج المصادقة وفق سياساتها. ونتلقى معلومات محدودة من الملف الشخصي لإنشاء حسابك أو تحديثه كما هو موضح أعلاه." },
      { h: "ملفات تعريف الارتباط وتقنيات الجلسة" },
      { p: "نستخدم ملفات تعريف الارتباط أو آليات جلسة مماثلة لازمة لتسجيل الدخول والأمان، ولتذكّر تفضيلاتك للغة والسمة والمظهر. وهي أساسية أو وظيفية وليست لتتبع الإعلانات." },
      { h: "الاحتفاظ بالبيانات" },
      { p: "نحتفظ ببيانات الحساب والسير الذاتية ما دام حسابك نشطًا وبالقدر اللازم لتقديم الخدمة. [PLACEHOLDER: حدد فترات الاحتفاظ والنسخ الاحتياطي وممارسات الحذف بمشورة قانونية.]" },
      { h: "الأمان" },
      { p: "نطبّق تدابير متوافقة مع معايير القطاع، مثل تجزئة كلمات المرور وضوابط الوصول من جهة الخادم والتحقق من الملكية في عمليات السير الذاتية. لا توجد وسيلة نقل أو تخزين آمنة تمامًا." },
      { h: "حقوقك" },
      { p: "بحسب مكان إقامتك، قد يحق لك الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها أو تصديرها. [PLACEHOLDER: صِف كيفية ممارسة الحقوق والمتطلبات الإقليمية بعد المراجعة القانونية. لا ندّعي الامتثال للائحة GDPR أو CCPA أو غيرهما ما لم يثبت ذلك رسميًا.]" },
      { h: "خصوصية الأطفال" },
      { p: "الخدمة غير موجهة للأطفال دون 13 عامًا (أو دون الحد الأدنى للسن في نطاقك القضائي). ولا نجمع عن علم معلومات شخصية من الأطفال. [PLACEHOLDER: عدّل الحد الأدنى للسن وفق القانون المعمول به.]" },
      { h: "التغييرات على هذه السياسة" },
      { p: "قد نحدّث سياسة الخصوصية هذه من وقت لآخر. وسننشر النسخة المحدثة على هذه الصفحة ونحدّث تاريخ \"آخر تحديث\". [PLACEHOLDER: صِف كيفية إخطار المستخدمين بالتغييرات الجوهرية.]" },
      { h: "التواصل" },
      { p: "للاستفسارات أو الطلبات المتعلقة بالخصوصية، تواصل عبر: [PLACEHOLDER: بريد إلكتروني أو نموذج تواصل للخصوصية]. [PLACEHOLDER: لا تذكر عنوان الكيان القانوني قبل تأكيده مع المستشار القانوني.]" },
    ],
  },
  zh: {
    title: "隐私政策",
    description: "{name} 隐私政策。",
    blocks: [
      { p: "本隐私政策说明 {name}（“我们”）在你使用我们的简历生成服务（“本服务”）时如何收集、使用和存储信息。本文件旨在保持透明。[PLACEHOLDER：请由合格的法律顾问根据你的司法管辖区和业务结构审核并定稿本政策。]" },
      { h: "我们收集的信息" },
      { p: "我们收集你直接提供的信息、你使用本服务过程中产生的信息，以及运行应用所需的有限技术数据。" },
      { h: "账户信息" },
      { p: "注册时，我们会收集你的姓名、邮箱地址以及经过哈希处理的密码（用于邮箱密码登录）。如果你使用 Google OAuth，我们会根据你的 Google 账户设置接收 Google 提供的个人资料信息（如姓名、邮箱和头像）。" },
      { h: "简历内容" },
      { p: "你在简历编辑器中输入的内容（包括工作经历、教育背景、技能、摘要及相关字段）会被存储，以便你编辑、保存和导出简历。提交哪些内容由你决定。" },
      { h: "身份验证信息" },
      { p: "我们使用 Auth.js（NextAuth）和基于 JWT 的会话。会话令牌及相关身份验证数据用于保持你的登录状态，并保护对你的账户和简历的访问。" },
      { h: "AI 处理" },
      { p: "当 AI 功能已启用且你选择使用时，你提交的相关文本（如摘要或经历描述）可能会被发送至已配置的 AI 服务商（例如兼容 OpenAI 的 API）以生成建议。建议需经你确认后才会应用。请勿提交你不希望由第三方 AI 服务处理的敏感个人数据。" },
      { h: "PDF 生成" },
      { p: "PDF 导出在我们的服务器上根据你已保存的简历数据和所选模板生成。导出请求需要经过身份验证和所有权校验；未经这些控制，我们不会根据客户端任意提交的内容生成 PDF。" },
      { h: "我们如何使用信息" },
      { ul: ["提供、维护和改进本服务", "验证用户身份并控制对简历的访问", "保存和同步你的简历内容", "在你请求时生成 AI 建议", "在你请求时生成 PDF 导出文件", "在适用情况下回应支持或法律请求"] },
      { h: "数据存储" },
      { p: "账户和简历数据存储在由部署所配置的服务商托管的 MongoDB（或兼容数据库）中（例如 MongoDB Atlas）。数据所在位置取决于数据库托管区域和服务商设置。" },
      { h: "第三方服务" },
      { p: "本服务可能依赖以下第三方：" },
      { ul: ["托管服务（例如 Vercel）", "数据库托管（例如 MongoDB Atlas）", "身份验证（启用时的 Google OAuth）", "AI 服务商（配置 API 密钥时）"] },
      { p: "各服务商按其自身条款和隐私政策处理数据。[PLACEHOLDER：列出生产环境中使用的具体服务商及链接。]" },
      { h: "Google OAuth" },
      { p: "如果你使用 Google 登录，Google 将按照其政策处理你的身份验证。我们会接收有限的个人资料信息，以按上述方式创建或更新你的账户。" },
      { h: "Cookie 与会话技术" },
      { p: "我们使用登录和安全所必需的 Cookie 或类似会话机制，并用其记住你的语言、主题和外观偏好。这些属于必要或功能性用途，并非用于广告追踪。" },
      { h: "数据保留" },
      { p: "在你的账户有效期间以及提供本服务所需的范围内，我们会保留账户和简历数据。[PLACEHOLDER：在法律意见下确定保留期限、备份保留及删除做法。]" },
      { h: "安全" },
      { p: "我们采用行业标准措施，例如密码哈希、服务器端访问控制以及简历操作的所有权校验。任何传输或存储方式都无法做到绝对安全。" },
      { h: "你的权利" },
      { p: "根据你所在地区，你可能有权访问、更正、删除或导出个人数据。[PLACEHOLDER：经法律审核后说明如何行使权利及地区性要求。除非正式确立，否则我们不声称符合 GDPR、CCPA 或其他法规。]" },
      { h: "儿童隐私" },
      { p: "本服务不面向 13 岁以下（或你所在司法管辖区最低年龄以下）的儿童。我们不会在知情的情况下收集儿童的个人信息。[PLACEHOLDER：根据适用法律调整年龄门槛。]" },
      { h: "本政策的变更" },
      { p: "我们可能会不时更新本隐私政策，并在本页面发布更新版本、更新“最后更新”日期。[PLACEHOLDER：说明将如何通知用户重大变更。]" },
      { h: "联系方式" },
      { p: "如有隐私相关问题或请求，请联系：[PLACEHOLDER：隐私联系邮箱或网页表单]。[PLACEHOLDER：在与法律顾问确认前，请勿列出法律实体地址。]" },
    ],
  },
};
