import type { Locale } from "@/lib/i18n/preferences";
import type { LegalDocument } from "@/lib/legal/types";
import * as it from "@/lib/legal/translations/it";
import * as nl from "@/lib/legal/translations/nl";
import * as pl from "@/lib/legal/translations/pl";
import * as pt from "@/lib/legal/translations/pt";
import * as ru from "@/lib/legal/translations/ru";
import * as tr from "@/lib/legal/translations/tr";

/** `{name}` is replaced with the product name when rendered. */
export const TERMS_AND_CONDITIONS: Record<Locale, LegalDocument> = {
  en: {
    title: "Terms & Conditions",
    description: "Terms and Conditions for {name}.",
    blocks: [
      { p: 'These Terms & Conditions ("Terms") govern your access to and use of {name} (the "Service"). By using the Service, you agree to these Terms. [PLACEHOLDER: have qualified legal counsel review and finalize these Terms for your business and jurisdiction.]' },
      { h: "Acceptance of terms" },
      { p: "If you do not agree to these Terms, do not use the Service. We may update these Terms; continued use after changes constitutes acceptance of the updated Terms where permitted by law." },
      { h: "Account creation" },
      { p: "You must provide accurate registration information and keep your credentials secure. You are responsible for activity under your account. You must be old enough to form a binding contract in your jurisdiction." },
      { h: "User responsibilities" },
      { ul: ["Use the Service lawfully and in good faith", "Ensure CV content you submit is accurate to the best of your knowledge", "Do not attempt to access other users' CVs or accounts", "Do not disrupt or reverse engineer the Service"] },
      { h: "CV content ownership" },
      { p: "You retain ownership of the CV content you create. You grant us a limited license to host, process, and display your content solely to operate the Service (including saving, rendering templates, AI assist when requested, and PDF export)." },
      { h: "Acceptable use" },
      { p: "You may not use the Service to upload unlawful, infringing, harassing, or malicious content, or to misrepresent qualifications in a way that violates applicable law or professional obligations." },
      { h: "AI-generated content limitations" },
      { p: "AI suggestions are provided for convenience. They may be inaccurate or incomplete. You are responsible for reviewing and editing any AI output before using it in applications or submissions. We do not guarantee hiring outcomes or employer acceptance of AI-assisted text." },
      { h: "PDF and export functionality" },
      { p: "PDF exports reflect your saved CV at the time of export. Layout may differ slightly from on-screen previews. You are responsible for verifying the exported document before sharing it." },
      { h: "Intellectual property" },
      { p: "The Service, including software, templates, branding, and documentation (excluding your CV content), is owned by us or our licensors and protected by applicable intellectual property laws. [PLACEHOLDER: specify ownership entity when established.]" },
      { h: "Third-party services" },
      { p: "The Service integrates with third parties (hosting, database, OAuth, AI providers). Your use of those features may be subject to third-party terms. We are not responsible for third-party services outside our reasonable control." },
      { h: "Availability" },
      { p: "We strive for reliable operation but do not guarantee uninterrupted or error-free access. Maintenance, updates, or infrastructure issues may cause temporary unavailability." },
      { h: "Disclaimer" },
      { p: 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, TO THE FULLEST EXTENT PERMITTED BY LAW. [PLACEHOLDER: legal review required for warranty disclaimers in your jurisdiction.]' },
      { h: "Limitation of liability" },
      { p: "TO THE FULLEST EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE. [PLACEHOLDER: cap and exceptions must be set with legal advice.]" },
      { h: "Account termination" },
      { p: "You may stop using the Service at any time. We may suspend or terminate access for violations of these Terms or to protect the Service. [PLACEHOLDER: describe data handling on termination.]" },
      { h: "Changes to terms" },
      { p: "We may modify these Terms. Material changes will be posted on this page with an updated date. [PLACEHOLDER: notification process.]" },
      { h: "Governing law" },
      { p: '[PLACEHOLDER: governing law and venue, e.g., "These Terms are governed by the laws of [Jurisdiction], without regard to conflict of law principles." Do not specify until confirmed with counsel.]' },
      { h: "Contact" },
      { p: "Questions about these Terms: [PLACEHOLDER: contact email or support channel]. [PLACEHOLDER: legal entity name and registered address if applicable.]" },
    ],
  },
  es: {
    title: "Términos y condiciones",
    description: "Términos y condiciones de {name}.",
    blocks: [
      { p: 'Estos Términos y condiciones ("Términos") regulan tu acceso y uso de {name} (el "Servicio"). Al usar el Servicio, aceptas estos Términos. [PLACEHOLDER: un asesor jurídico cualificado debe revisar y finalizar estos Términos para tu empresa y jurisdicción.]' },
      { h: "Aceptación de los términos" },
      { p: "Si no aceptas estos Términos, no uses el Servicio. Podemos actualizar estos Términos; el uso continuado tras los cambios supone la aceptación de los Términos actualizados cuando la ley lo permita." },
      { h: "Creación de cuenta" },
      { p: "Debes facilitar información de registro exacta y mantener tus credenciales seguras. Eres responsable de la actividad de tu cuenta. Debes tener edad suficiente para celebrar un contrato vinculante en tu jurisdicción." },
      { h: "Responsabilidades del usuario" },
      { ul: ["Usar el Servicio de forma lícita y de buena fe", "Asegurarte de que el contenido de tu CV sea exacto según tu leal saber y entender", "No intentar acceder a los CV o cuentas de otros usuarios", "No interrumpir ni aplicar ingeniería inversa al Servicio"] },
      { h: "Propiedad del contenido del CV" },
      { p: "Conservas la propiedad del contenido de los CV que creas. Nos concedes una licencia limitada para alojar, procesar y mostrar tu contenido únicamente para operar el Servicio (incluidos el guardado, la representación de plantillas, la asistencia de IA cuando la solicites y la exportación a PDF)." },
      { h: "Uso aceptable" },
      { p: "No puedes usar el Servicio para subir contenido ilícito, infractor, acosador o malicioso, ni para tergiversar cualificaciones de forma que infrinja la ley aplicable u obligaciones profesionales." },
      { h: "Limitaciones del contenido generado por IA" },
      { p: "Las sugerencias de IA se ofrecen por comodidad y pueden ser inexactas o incompletas. Eres responsable de revisar y editar cualquier resultado de la IA antes de usarlo en candidaturas o envíos. No garantizamos resultados de contratación ni que los empleadores acepten textos asistidos por IA." },
      { h: "PDF y funciones de exportación" },
      { p: "Las exportaciones PDF reflejan tu CV guardado en el momento de la exportación. El diseño puede diferir ligeramente de la vista previa en pantalla. Eres responsable de verificar el documento exportado antes de compartirlo." },
      { h: "Propiedad intelectual" },
      { p: "El Servicio, incluidos el software, las plantillas, la marca y la documentación (excluido el contenido de tu CV), es propiedad nuestra o de nuestros licenciantes y está protegido por las leyes de propiedad intelectual aplicables. [PLACEHOLDER: especificar la entidad titular cuando se constituya.]" },
      { h: "Servicios de terceros" },
      { p: "El Servicio se integra con terceros (alojamiento, base de datos, OAuth, proveedores de IA). El uso de esas funciones puede estar sujeto a condiciones de terceros. No somos responsables de servicios de terceros fuera de nuestro control razonable." },
      { h: "Disponibilidad" },
      { p: "Procuramos un funcionamiento fiable, pero no garantizamos un acceso ininterrumpido ni libre de errores. El mantenimiento, las actualizaciones o incidencias de infraestructura pueden provocar indisponibilidad temporal." },
      { h: "Exención de garantías" },
      { p: 'EL SERVICIO SE PROPORCIONA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD", SIN GARANTÍAS DE NINGÚN TIPO, EXPRESAS O IMPLÍCITAS, EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY. [PLACEHOLDER: se requiere revisión jurídica de las exenciones de garantía en tu jurisdicción.]' },
      { h: "Limitación de responsabilidad" },
      { p: "EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, NO SEREMOS RESPONSABLES DE DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENTES O PUNITIVOS, NI DE PÉRDIDAS DE BENEFICIOS, DATOS O FONDO DE COMERCIO DERIVADAS DEL USO DEL SERVICIO. [PLACEHOLDER: fijar límites y excepciones con asesoramiento jurídico.]" },
      { h: "Cancelación de la cuenta" },
      { p: "Puedes dejar de usar el Servicio en cualquier momento. Podemos suspender o cancelar el acceso por incumplimiento de estos Términos o para proteger el Servicio. [PLACEHOLDER: describir el tratamiento de los datos tras la cancelación.]" },
      { h: "Cambios en los términos" },
      { p: "Podemos modificar estos Términos. Los cambios importantes se publicarán en esta página con una fecha actualizada. [PLACEHOLDER: proceso de notificación.]" },
      { h: "Legislación aplicable" },
      { p: '[PLACEHOLDER: legislación y jurisdicción aplicables, p. ej., "Estos Términos se rigen por las leyes de [Jurisdicción], sin tener en cuenta las normas sobre conflictos de leyes." No especificar hasta confirmarlo con un asesor.]' },
      { h: "Contacto" },
      { p: "Consultas sobre estos Términos: [PLACEHOLDER: correo de contacto o canal de soporte]. [PLACEHOLDER: nombre de la entidad legal y domicilio social, si procede.]" },
    ],
  },
  fr: {
    title: "Conditions générales",
    description: "Conditions générales de {name}.",
    blocks: [
      { p: "Les présentes Conditions générales (les « Conditions ») régissent votre accès à {name} (le « Service ») et son utilisation. En utilisant le Service, vous acceptez ces Conditions. [PLACEHOLDER : faire relire et finaliser ces Conditions par un juriste qualifié pour votre activité et votre juridiction.]" },
      { h: "Acceptation des conditions" },
      { p: "Si vous n'acceptez pas ces Conditions, n'utilisez pas le Service. Nous pouvons mettre à jour ces Conditions ; la poursuite de l'utilisation après modification vaut acceptation des Conditions mises à jour lorsque la loi le permet." },
      { h: "Création de compte" },
      { p: "Vous devez fournir des informations d'inscription exactes et préserver la sécurité de vos identifiants. Vous êtes responsable de l'activité de votre compte. Vous devez avoir l'âge requis pour conclure un contrat contraignant dans votre juridiction." },
      { h: "Responsabilités de l'utilisateur" },
      { ul: ["Utiliser le Service de manière licite et de bonne foi", "Veiller à l'exactitude du contenu de votre CV au mieux de vos connaissances", "Ne pas tenter d'accéder aux CV ou comptes d'autres utilisateurs", "Ne pas perturber le Service ni en faire de l'ingénierie inverse"] },
      { h: "Propriété du contenu des CV" },
      { p: "Vous restez propriétaire du contenu de vos CV. Vous nous accordez une licence limitée pour héberger, traiter et afficher ce contenu dans le seul but d'exploiter le Service (enregistrement, rendu des modèles, assistance IA à votre demande et export PDF)." },
      { h: "Utilisation acceptable" },
      { p: "Vous ne pouvez pas utiliser le Service pour publier des contenus illicites, contrefaisants, harcelants ou malveillants, ni pour présenter faussement des qualifications en violation de la loi ou d'obligations professionnelles." },
      { h: "Limites du contenu généré par l'IA" },
      { p: "Les suggestions de l'IA sont fournies par commodité et peuvent être inexactes ou incomplètes. Il vous appartient de relire et de modifier tout résultat de l'IA avant de l'utiliser dans vos candidatures. Nous ne garantissons ni résultat d'embauche ni l'acceptation de textes assistés par IA par les employeurs." },
      { h: "PDF et fonctions d'export" },
      { p: "Les exports PDF reflètent votre CV enregistré au moment de l'export. La mise en page peut légèrement différer de l'aperçu à l'écran. Il vous appartient de vérifier le document exporté avant de le partager." },
      { h: "Propriété intellectuelle" },
      { p: "Le Service, y compris le logiciel, les modèles, l'identité visuelle et la documentation (hors contenu de vos CV), nous appartient ou appartient à nos concédants et est protégé par les lois applicables en matière de propriété intellectuelle. [PLACEHOLDER : préciser l'entité titulaire une fois constituée.]" },
      { h: "Services tiers" },
      { p: "Le Service s'intègre à des tiers (hébergement, base de données, OAuth, fournisseurs d'IA). L'utilisation de ces fonctions peut être soumise à leurs conditions. Nous ne sommes pas responsables des services tiers échappant à notre contrôle raisonnable." },
      { h: "Disponibilité" },
      { p: "Nous visons un fonctionnement fiable mais ne garantissons pas un accès ininterrompu ou exempt d'erreurs. La maintenance, les mises à jour ou des incidents d'infrastructure peuvent entraîner une indisponibilité temporaire." },
      { h: "Exclusion de garantie" },
      { p: "LE SERVICE EST FOURNI « EN L'ÉTAT » ET « SELON DISPONIBILITÉ », SANS GARANTIE D'AUCUNE SORTE, EXPRESSE OU IMPLICITE, DANS TOUTE LA MESURE PERMISE PAR LA LOI. [PLACEHOLDER : revue juridique nécessaire des exclusions de garantie dans votre juridiction.]" },
      { h: "Limitation de responsabilité" },
      { p: "DANS TOUTE LA MESURE PERMISE PAR LA LOI, NOUS NE SAURIONS ÊTRE TENUS RESPONSABLES DES DOMMAGES INDIRECTS, ACCESSOIRES, SPÉCIAUX, CONSÉCUTIFS OU PUNITIFS, NI DE TOUTE PERTE DE BÉNÉFICES, DE DONNÉES OU DE CLIENTÈLE RÉSULTANT DE VOTRE UTILISATION DU SERVICE. [PLACEHOLDER : plafond et exceptions à définir avec un conseil juridique.]" },
      { h: "Résiliation du compte" },
      { p: "Vous pouvez cesser d'utiliser le Service à tout moment. Nous pouvons suspendre ou résilier l'accès en cas de violation des présentes Conditions ou pour protéger le Service. [PLACEHOLDER : décrire le traitement des données à la résiliation.]" },
      { h: "Modification des conditions" },
      { p: "Nous pouvons modifier ces Conditions. Les modifications importantes seront publiées sur cette page avec une date mise à jour. [PLACEHOLDER : procédure de notification.]" },
      { h: "Droit applicable" },
      { p: "[PLACEHOLDER : droit applicable et juridiction compétente, par ex. « Les présentes Conditions sont régies par le droit de [Juridiction], sans égard aux règles de conflit de lois. » Ne pas préciser avant validation par un juriste.]" },
      { h: "Contact" },
      { p: "Questions sur ces Conditions : [PLACEHOLDER : e-mail de contact ou canal d'assistance]. [PLACEHOLDER : dénomination et siège de l'entité juridique le cas échéant.]" },
    ],
  },
  de: {
    title: "Allgemeine Geschäftsbedingungen",
    description: "Allgemeine Geschäftsbedingungen von {name}.",
    blocks: [
      { p: "Diese Allgemeinen Geschäftsbedingungen („Bedingungen“) regeln Ihren Zugang zu und Ihre Nutzung von {name} (dem „Dienst“). Mit der Nutzung des Dienstes stimmen Sie diesen Bedingungen zu. [PLACEHOLDER: Diese Bedingungen von einer qualifizierten Rechtsberatung für Ihr Unternehmen und Ihre Rechtsordnung prüfen und finalisieren lassen.]" },
      { h: "Annahme der Bedingungen" },
      { p: "Wenn Sie diesen Bedingungen nicht zustimmen, nutzen Sie den Dienst nicht. Wir können diese Bedingungen aktualisieren; die weitere Nutzung nach Änderungen gilt, soweit gesetzlich zulässig, als Zustimmung zu den aktualisierten Bedingungen." },
      { h: "Kontoerstellung" },
      { p: "Sie müssen zutreffende Registrierungsdaten angeben und Ihre Zugangsdaten sicher aufbewahren. Sie sind für Aktivitäten in Ihrem Konto verantwortlich. Sie müssen alt genug sein, um in Ihrer Rechtsordnung einen verbindlichen Vertrag abzuschließen." },
      { h: "Pflichten der Nutzer" },
      { ul: ["Den Dienst rechtmäßig und nach Treu und Glauben nutzen", "Sicherstellen, dass Ihre Lebenslaufinhalte nach bestem Wissen zutreffen", "Nicht versuchen, auf Lebensläufe oder Konten anderer Nutzer zuzugreifen", "Den Dienst nicht stören oder per Reverse Engineering untersuchen"] },
      { h: "Eigentum an Lebenslaufinhalten" },
      { p: "Sie bleiben Eigentümer der von Ihnen erstellten Lebenslaufinhalte. Sie räumen uns eine beschränkte Lizenz ein, Ihre Inhalte ausschließlich zum Betrieb des Dienstes zu hosten, zu verarbeiten und anzuzeigen (einschließlich Speichern, Darstellung von Vorlagen, KI-Unterstützung auf Anfrage und PDF-Export)." },
      { h: "Zulässige Nutzung" },
      { p: "Sie dürfen den Dienst nicht nutzen, um rechtswidrige, rechtsverletzende, belästigende oder schädliche Inhalte hochzuladen oder Qualifikationen in einer Weise falsch darzustellen, die gegen geltendes Recht oder berufliche Pflichten verstößt." },
      { h: "Grenzen KI-generierter Inhalte" },
      { p: "KI-Vorschläge dienen der Bequemlichkeit und können ungenau oder unvollständig sein. Sie sind dafür verantwortlich, KI-Ergebnisse vor der Verwendung in Bewerbungen zu prüfen und zu bearbeiten. Wir garantieren weder Einstellungserfolge noch die Akzeptanz KI-gestützter Texte durch Arbeitgeber." },
      { h: "PDF- und Exportfunktionen" },
      { p: "PDF-Exporte spiegeln Ihren gespeicherten Lebenslauf zum Zeitpunkt des Exports wider. Das Layout kann leicht von der Bildschirmvorschau abweichen. Sie sind dafür verantwortlich, das exportierte Dokument vor dem Teilen zu prüfen." },
      { h: "Geistiges Eigentum" },
      { p: "Der Dienst einschließlich Software, Vorlagen, Markenauftritt und Dokumentation (ausgenommen Ihre Lebenslaufinhalte) gehört uns oder unseren Lizenzgebern und ist durch geltendes Recht des geistigen Eigentums geschützt. [PLACEHOLDER: Rechteinhaber angeben, sobald gegründet.]" },
      { h: "Dienste Dritter" },
      { p: "Der Dienst ist mit Dritten verbunden (Hosting, Datenbank, OAuth, KI-Anbieter). Die Nutzung dieser Funktionen kann Bedingungen Dritter unterliegen. Für Dienste Dritter außerhalb unseres zumutbaren Einflussbereichs sind wir nicht verantwortlich." },
      { h: "Verfügbarkeit" },
      { p: "Wir streben einen zuverlässigen Betrieb an, garantieren jedoch keinen unterbrechungs- oder fehlerfreien Zugang. Wartung, Updates oder Infrastrukturprobleme können zu vorübergehender Nichtverfügbarkeit führen." },
      { h: "Haftungsausschluss" },
      { p: "DER DIENST WIRD, SOWEIT GESETZLICH ZULÄSSIG, „WIE BESEHEN“ UND „WIE VERFÜGBAR“ OHNE AUSDRÜCKLICHE ODER STILLSCHWEIGENDE GEWÄHRLEISTUNG BEREITGESTELLT. [PLACEHOLDER: Gewährleistungsausschlüsse für Ihre Rechtsordnung rechtlich prüfen lassen.]" },
      { h: "Haftungsbeschränkung" },
      { p: "SOWEIT GESETZLICH ZULÄSSIG, HAFTEN WIR NICHT FÜR INDIREKTE, BEILÄUFIGE, BESONDERE, FOLGE- ODER STRAFSCHÄDEN SOWIE FÜR ENTGANGENE GEWINNE, DATENVERLUSTE ODER RUFSCHÄDEN, DIE AUS IHRER NUTZUNG DES DIENSTES ENTSTEHEN. [PLACEHOLDER: Haftungsgrenzen und Ausnahmen mit Rechtsberatung festlegen.]" },
      { h: "Kündigung des Kontos" },
      { p: "Sie können die Nutzung des Dienstes jederzeit beenden. Wir können den Zugang bei Verstößen gegen diese Bedingungen oder zum Schutz des Dienstes sperren oder beenden. [PLACEHOLDER: Umgang mit Daten nach Kündigung beschreiben.]" },
      { h: "Änderungen der Bedingungen" },
      { p: "Wir können diese Bedingungen ändern. Wesentliche Änderungen werden auf dieser Seite mit aktualisiertem Datum veröffentlicht. [PLACEHOLDER: Benachrichtigungsverfahren.]" },
      { h: "Anwendbares Recht" },
      { p: "[PLACEHOLDER: anwendbares Recht und Gerichtsstand, z. B. „Diese Bedingungen unterliegen dem Recht von [Rechtsordnung] unter Ausschluss der Kollisionsnormen.“ Erst nach Bestätigung durch Rechtsberatung angeben.]" },
      { h: "Kontakt" },
      { p: "Fragen zu diesen Bedingungen: [PLACEHOLDER: Kontakt-E-Mail oder Supportkanal]. [PLACEHOLDER: Name und Sitz der juristischen Person, falls zutreffend.]" },
    ],
  },
  ar: {
    title: "الشروط والأحكام",
    description: "الشروط والأحكام الخاصة بـ {name}.",
    blocks: [
      { p: "تحكم هذه الشروط والأحكام (\"الشروط\") وصولك إلى {name} (\"الخدمة\") واستخدامك لها. باستخدامك للخدمة، فإنك توافق على هذه الشروط. [PLACEHOLDER: يجب أن يراجع مستشار قانوني مؤهل هذه الشروط ويعتمدها وفق نشاطك التجاري ونطاقك القضائي.]" },
      { h: "قبول الشروط" },
      { p: "إذا كنت لا توافق على هذه الشروط، فلا تستخدم الخدمة. قد نحدّث هذه الشروط، ويُعد استمرارك في الاستخدام بعد التغييرات قبولًا للشروط المحدثة حيثما يسمح القانون." },
      { h: "إنشاء الحساب" },
      { p: "يجب عليك تقديم معلومات تسجيل دقيقة والحفاظ على أمان بيانات الدخول. أنت مسؤول عن النشاط الذي يتم عبر حسابك. ويجب أن تكون قد بلغت السن التي تخولك إبرام عقد ملزم في نطاقك القضائي." },
      { h: "مسؤوليات المستخدم" },
      { ul: ["استخدام الخدمة بشكل قانوني وبحسن نية", "التأكد من دقة محتوى سيرتك الذاتية قدر علمك", "عدم محاولة الوصول إلى سير أو حسابات المستخدمين الآخرين", "عدم تعطيل الخدمة أو إجراء هندسة عكسية لها"] },
      { h: "ملكية محتوى السيرة الذاتية" },
      { p: "تحتفظ بملكية محتوى السيرة الذاتية الذي تنشئه. وتمنحنا ترخيصًا محدودًا لاستضافة محتواك ومعالجته وعرضه لغرض تشغيل الخدمة فقط (بما في ذلك الحفظ وعرض القوالب ومساعدة الذكاء الاصطناعي عند الطلب وتصدير PDF)." },
      { h: "الاستخدام المقبول" },
      { p: "لا يجوز لك استخدام الخدمة لرفع محتوى غير قانوني أو منتهك للحقوق أو مسيء أو ضار، أو لتقديم مؤهلات مضللة بما يخالف القانون المعمول به أو الالتزامات المهنية." },
      { h: "حدود المحتوى المُنشأ بالذكاء الاصطناعي" },
      { p: "تُقدَّم اقتراحات الذكاء الاصطناعي للتيسير، وقد تكون غير دقيقة أو غير مكتملة. أنت مسؤول عن مراجعة أي مخرجات للذكاء الاصطناعي وتعديلها قبل استخدامها في طلبات التوظيف. ولا نضمن نتائج التوظيف أو قبول أصحاب العمل للنصوص المدعومة بالذكاء الاصطناعي." },
      { h: "ملفات PDF ووظائف التصدير" },
      { p: "تعكس ملفات PDF المصدّرة سيرتك الذاتية المحفوظة وقت التصدير. وقد يختلف التخطيط قليلًا عن المعاينة على الشاشة. أنت مسؤول عن التحقق من المستند المصدّر قبل مشاركته." },
      { h: "الملكية الفكرية" },
      { p: "الخدمة، بما في ذلك البرمجيات والقوالب والعلامة التجارية والوثائق (باستثناء محتوى سيرتك الذاتية)، مملوكة لنا أو للجهات المرخِّصة لنا ومحمية بقوانين الملكية الفكرية المعمول بها. [PLACEHOLDER: حدد الجهة المالكة عند تأسيسها.]" },
      { h: "خدمات الجهات الخارجية" },
      { p: "تتكامل الخدمة مع جهات خارجية (الاستضافة وقاعدة البيانات وOAuth ومزوّدي الذكاء الاصطناعي). وقد يخضع استخدامك لتلك الميزات لشروط تلك الجهات. ولسنا مسؤولين عن خدمات الجهات الخارجية الخارجة عن سيطرتنا المعقولة." },
      { h: "التوفر" },
      { p: "نسعى إلى تشغيل موثوق، لكننا لا نضمن وصولًا متواصلًا أو خاليًا من الأخطاء. وقد تؤدي الصيانة أو التحديثات أو مشكلات البنية التحتية إلى عدم توفر مؤقت." },
      { h: "إخلاء المسؤولية" },
      { p: "تُقدَّم الخدمة \"كما هي\" و\"حسب توفرها\" دون أي ضمانات من أي نوع، صريحة كانت أو ضمنية، إلى أقصى حد يسمح به القانون. [PLACEHOLDER: يلزم إجراء مراجعة قانونية لإخلاءات الضمان في نطاقك القضائي.]" },
      { h: "تحديد المسؤولية" },
      { p: "إلى أقصى حد يسمح به القانون، لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية، أو عن أي خسارة في الأرباح أو البيانات أو السمعة تنشأ عن استخدامك للخدمة. [PLACEHOLDER: يجب تحديد الحد الأقصى والاستثناءات بمشورة قانونية.]" },
      { h: "إنهاء الحساب" },
      { p: "يمكنك التوقف عن استخدام الخدمة في أي وقت. ويجوز لنا تعليق الوصول أو إنهاؤه عند مخالفة هذه الشروط أو لحماية الخدمة. [PLACEHOLDER: صِف كيفية التعامل مع البيانات عند الإنهاء.]" },
      { h: "التغييرات على الشروط" },
      { p: "قد نعدّل هذه الشروط. وستُنشر التغييرات الجوهرية على هذه الصفحة مع تاريخ محدث. [PLACEHOLDER: آلية الإخطار.]" },
      { h: "القانون الحاكم" },
      { p: "[PLACEHOLDER: القانون الحاكم ومكان الاختصاص، مثل: \"تخضع هذه الشروط لقوانين [النطاق القضائي] بصرف النظر عن مبادئ تنازع القوانين.\" لا تحدده قبل التأكيد مع المستشار القانوني.]" },
      { h: "التواصل" },
      { p: "للاستفسارات حول هذه الشروط: [PLACEHOLDER: بريد التواصل أو قناة الدعم]. [PLACEHOLDER: اسم الكيان القانوني وعنوانه المسجل إن وُجد.]" },
    ],
  },
  zh: {
    title: "条款与条件",
    description: "{name} 条款与条件。",
    blocks: [
      { p: "本条款与条件（“本条款”）规范你对 {name}（“本服务”）的访问和使用。使用本服务即表示你同意本条款。[PLACEHOLDER：请由合格的法律顾问根据你的业务和司法管辖区审核并定稿本条款。]" },
      { h: "接受条款" },
      { p: "如果你不同意本条款，请勿使用本服务。我们可能会更新本条款；在法律允许的范围内，变更后继续使用即视为接受更新后的条款。" },
      { h: "账户创建" },
      { p: "你必须提供准确的注册信息并妥善保管登录凭据。你需对账户下的活动负责。你必须达到所在司法管辖区可订立有约束力合同的年龄。" },
      { h: "用户责任" },
      { ul: ["合法、诚信地使用本服务", "尽你所知确保所提交的简历内容准确", "不得试图访问其他用户的简历或账户", "不得干扰本服务或对其进行逆向工程"] },
      { h: "简历内容的所有权" },
      { p: "你保留所创建简历内容的所有权。你授予我们有限许可，仅为运营本服务而托管、处理和展示你的内容（包括保存、渲染模板、应你请求提供 AI 辅助以及导出 PDF）。" },
      { h: "可接受的使用" },
      { p: "你不得利用本服务上传违法、侵权、骚扰或恶意内容，也不得以违反适用法律或职业义务的方式虚报资历。" },
      { h: "AI 生成内容的局限" },
      { p: "AI 建议仅为方便而提供，可能不准确或不完整。在将任何 AI 输出用于求职申请前，你有责任对其进行审核和修改。我们不保证招聘结果，也不保证雇主接受 AI 辅助撰写的文本。" },
      { h: "PDF 与导出功能" },
      { p: "PDF 导出反映导出时你已保存的简历。版式可能与屏幕预览略有差异。在分享前核对导出的文档是你的责任。" },
      { h: "知识产权" },
      { p: "本服务（包括软件、模板、品牌和文档，但不包括你的简历内容）归我们或我们的许可方所有，并受适用的知识产权法律保护。[PLACEHOLDER：确立后注明权利主体。]" },
      { h: "第三方服务" },
      { p: "本服务集成了第三方（托管、数据库、OAuth、AI 服务商）。你对这些功能的使用可能受第三方条款约束。对于超出我们合理控制范围的第三方服务，我们不承担责任。" },
      { h: "可用性" },
      { p: "我们力求稳定运行，但不保证访问不中断或无错误。维护、更新或基础设施问题可能导致暂时不可用。" },
      { h: "免责声明" },
      { p: "在法律允许的最大范围内，本服务按“现状”和“现有”提供，不附带任何明示或默示的保证。[PLACEHOLDER：需针对你所在司法管辖区的免责条款进行法律审核。]" },
      { h: "责任限制" },
      { p: "在法律允许的最大范围内，对于因你使用本服务而产生的任何间接、附带、特殊、后果性或惩罚性损害，或任何利润、数据或商誉损失，我们概不负责。[PLACEHOLDER：赔偿上限及例外须在法律意见下确定。]" },
      { h: "账户终止" },
      { p: "你可随时停止使用本服务。如你违反本条款或为保护本服务，我们可暂停或终止你的访问。[PLACEHOLDER：说明终止后的数据处理方式。]" },
      { h: "条款变更" },
      { p: "我们可能修改本条款。重大变更将在本页面发布并更新日期。[PLACEHOLDER：通知流程。]" },
      { h: "适用法律" },
      { p: "[PLACEHOLDER：适用法律及管辖地，例如“本条款受[司法管辖区]法律管辖，不考虑法律冲突原则。”在与法律顾问确认前请勿指定。]" },
      { h: "联系方式" },
      { p: "关于本条款的问题：[PLACEHOLDER：联系邮箱或支持渠道]。[PLACEHOLDER：如适用，填写法律实体名称及注册地址。]" },
    ],
  },
  pt: pt.terms,
  it: it.terms,
  nl: nl.terms,
  pl: pl.terms,
  tr: tr.terms,
  ru: ru.terms,
};
