export const RESUME_IMPORT_MIN_PARSE_TEXT_LENGTH = 40;

export const RESUME_IMPORT_PARSE_MAX_FIELD_LENGTH = 2_000;
export const RESUME_IMPORT_PARSE_MAX_SUMMARY_LENGTH = 10_000;
export const RESUME_IMPORT_PARSE_MAX_DESCRIPTION_LENGTH = 10_000;
export const RESUME_IMPORT_PARSE_MAX_SKILL_LENGTH = 120;

export const RESUME_IMPORT_PARSE_MAX_WORK_ENTRIES = 40;
export const RESUME_IMPORT_PARSE_MAX_EDUCATION_ENTRIES = 40;
export const RESUME_IMPORT_PARSE_MAX_SKILLS = 80;
export const RESUME_IMPORT_PARSE_MAX_PROJECTS = 30;
export const RESUME_IMPORT_PARSE_MAX_CERTIFICATIONS = 30;
export const RESUME_IMPORT_PARSE_MAX_LANGUAGES = 30;

export const RESUME_IMPORT_PARSE_TIMEOUT_MS = 90_000;
